import { IDOC_REGIONS } from './validation.ts';

type IdocRegion = (typeof IDOC_REGIONS)[number];

/**
 * Default IDOC Region for each ISO 3166-1 alpha-2 country, used only to pre-select a sensible
 * starting value when a member picks their address country -- the member can always change it
 * manually afterward (see onboarding-wizard.tsx's federationWasManuallyEdited-style tracking).
 * IDOC_REGIONS groups countries more coarsely than by continent (e.g. "Western Europe & Africa" is
 * one region, Mexico groups with "Central & Latin America" rather than "North America"), so this is
 * a maintained editorial mapping, not a derivable geography lookup.
 */
export const IDOC_REGION_BY_COUNTRY: Record<string, IdocRegion> = {
  AD: 'Western Europe & Africa', AE: 'Asia', AF: 'Asia', AG: 'Central & Latin America',
  AI: 'Central & Latin America', AL: 'Central & Eastern Europe', AM: 'Asia',
  AO: 'Western Europe & Africa', AQ: 'Pacific', AR: 'Central & Latin America', AS: 'Pacific',
  AT: 'Western Europe & Africa', AU: 'Pacific', AW: 'Central & Latin America',
  AX: 'Western Europe & Africa', AZ: 'Asia', BA: 'Central & Eastern Europe',
  BB: 'Central & Latin America', BD: 'Asia', BE: 'Western Europe & Africa',
  BF: 'Western Europe & Africa', BG: 'Central & Eastern Europe', BH: 'Asia',
  BI: 'Western Europe & Africa', BJ: 'Western Europe & Africa', BL: 'Central & Latin America',
  BM: 'North America', BN: 'Asia', BO: 'Central & Latin America',
  BQ: 'Central & Latin America', BR: 'Central & Latin America', BS: 'Central & Latin America',
  BT: 'Asia', BV: 'Western Europe & Africa', BW: 'Western Europe & Africa',
  BY: 'Central & Eastern Europe', BZ: 'Central & Latin America', CA: 'North America',
  CC: 'Pacific', CD: 'Western Europe & Africa', CF: 'Western Europe & Africa',
  CG: 'Western Europe & Africa', CH: 'Western Europe & Africa', CI: 'Western Europe & Africa',
  CK: 'Pacific', CL: 'Central & Latin America', CM: 'Western Europe & Africa', CN: 'Asia',
  CO: 'Central & Latin America', CR: 'Central & Latin America', CU: 'Central & Latin America',
  CV: 'Western Europe & Africa', CW: 'Central & Latin America', CX: 'Pacific',
  CY: 'Western Europe & Africa', CZ: 'Central & Eastern Europe', DE: 'Western Europe & Africa',
  DJ: 'Western Europe & Africa', DK: 'Western Europe & Africa', DM: 'Central & Latin America',
  DO: 'Central & Latin America', DZ: 'Western Europe & Africa', EC: 'Central & Latin America',
  EE: 'Central & Eastern Europe', EG: 'Western Europe & Africa', EH: 'Western Europe & Africa',
  ER: 'Western Europe & Africa', ES: 'Western Europe & Africa', ET: 'Western Europe & Africa',
  FI: 'Western Europe & Africa', FJ: 'Pacific', FK: 'Central & Latin America', FM: 'Pacific',
  FO: 'Western Europe & Africa', FR: 'Western Europe & Africa', GA: 'Western Europe & Africa',
  GB: 'Western Europe & Africa', GD: 'Central & Latin America', GE: 'Asia',
  GF: 'Central & Latin America', GG: 'Western Europe & Africa', GH: 'Western Europe & Africa',
  GI: 'Western Europe & Africa', GL: 'North America', GM: 'Western Europe & Africa',
  GN: 'Western Europe & Africa', GP: 'Central & Latin America', GQ: 'Western Europe & Africa',
  GR: 'Western Europe & Africa', GS: 'Central & Latin America', GT: 'Central & Latin America',
  GU: 'Pacific', GW: 'Western Europe & Africa', GY: 'Central & Latin America', HK: 'Asia',
  HM: 'Pacific', HN: 'Central & Latin America', HR: 'Central & Eastern Europe',
  HT: 'Central & Latin America', HU: 'Central & Eastern Europe', ID: 'Asia',
  IE: 'Western Europe & Africa', IL: 'Asia', IM: 'Western Europe & Africa', IN: 'Asia',
  IO: 'Asia', IQ: 'Asia', IR: 'Asia', IS: 'Western Europe & Africa', IT: 'Western Europe & Africa',
  JE: 'Western Europe & Africa', JM: 'Central & Latin America', JO: 'Asia', JP: 'Asia',
  KE: 'Western Europe & Africa', KG: 'Asia', KH: 'Asia', KI: 'Pacific',
  KM: 'Western Europe & Africa', KN: 'Central & Latin America', KP: 'Asia', KR: 'Asia',
  KW: 'Asia', KY: 'Central & Latin America', KZ: 'Asia', LA: 'Asia', LB: 'Asia',
  LC: 'Central & Latin America', LI: 'Western Europe & Africa', LK: 'Asia',
  LR: 'Western Europe & Africa', LS: 'Western Europe & Africa', LT: 'Central & Eastern Europe',
  LU: 'Western Europe & Africa', LV: 'Central & Eastern Europe', LY: 'Western Europe & Africa',
  MA: 'Western Europe & Africa', MC: 'Western Europe & Africa', MD: 'Central & Eastern Europe',
  ME: 'Central & Eastern Europe', MF: 'Central & Latin America', MG: 'Western Europe & Africa',
  MH: 'Pacific', MK: 'Central & Eastern Europe', ML: 'Western Europe & Africa', MM: 'Asia',
  MN: 'Asia', MO: 'Asia', MP: 'Pacific', MQ: 'Central & Latin America',
  MR: 'Western Europe & Africa', MS: 'Central & Latin America', MT: 'Western Europe & Africa',
  MU: 'Western Europe & Africa', MV: 'Asia', MW: 'Western Europe & Africa',
  MX: 'Central & Latin America', MY: 'Asia', MZ: 'Western Europe & Africa',
  NA: 'Western Europe & Africa', NC: 'Pacific', NE: 'Western Europe & Africa', NF: 'Pacific',
  NG: 'Western Europe & Africa', NI: 'Central & Latin America', NL: 'Western Europe & Africa',
  NO: 'Western Europe & Africa', NP: 'Asia', NR: 'Pacific', NU: 'Pacific', NZ: 'Pacific',
  OM: 'Asia', PA: 'Central & Latin America', PE: 'Central & Latin America', PF: 'Pacific',
  PG: 'Pacific', PH: 'Asia', PK: 'Asia', PL: 'Central & Eastern Europe', PM: 'North America',
  PN: 'Pacific', PR: 'Central & Latin America', PS: 'Asia', PT: 'Western Europe & Africa',
  PW: 'Pacific', PY: 'Central & Latin America', QA: 'Asia', RE: 'Western Europe & Africa',
  RO: 'Central & Eastern Europe', RS: 'Central & Eastern Europe', RU: 'Central & Eastern Europe',
  RW: 'Western Europe & Africa', SA: 'Asia', SB: 'Pacific', SC: 'Western Europe & Africa',
  SD: 'Western Europe & Africa', SE: 'Western Europe & Africa', SG: 'Asia',
  SH: 'Western Europe & Africa', SI: 'Central & Eastern Europe', SJ: 'Western Europe & Africa',
  SK: 'Central & Eastern Europe', SL: 'Western Europe & Africa', SM: 'Western Europe & Africa',
  SN: 'Western Europe & Africa', SO: 'Western Europe & Africa', SR: 'Central & Latin America',
  SS: 'Western Europe & Africa', ST: 'Western Europe & Africa', SV: 'Central & Latin America',
  SX: 'Central & Latin America', SY: 'Asia', SZ: 'Western Europe & Africa',
  TC: 'Central & Latin America', TD: 'Western Europe & Africa', TF: 'Western Europe & Africa',
  TG: 'Western Europe & Africa', TH: 'Asia', TJ: 'Asia', TK: 'Pacific', TL: 'Asia',
  TM: 'Asia', TN: 'Western Europe & Africa', TO: 'Pacific', TR: 'Central & Eastern Europe',
  TT: 'Central & Latin America', TV: 'Pacific', TW: 'Asia', TZ: 'Western Europe & Africa',
  UA: 'Central & Eastern Europe', UG: 'Western Europe & Africa', UM: 'Pacific',
  US: 'North America', UY: 'Central & Latin America', UZ: 'Asia',
  VA: 'Western Europe & Africa', VC: 'Central & Latin America', VE: 'Central & Latin America',
  VG: 'Central & Latin America', VI: 'Central & Latin America', VN: 'Asia', VU: 'Pacific',
  WF: 'Pacific', WS: 'Pacific', YE: 'Asia', YT: 'Western Europe & Africa',
  ZA: 'Western Europe & Africa', ZM: 'Western Europe & Africa', ZW: 'Western Europe & Africa',
};
