-- IDOC TABLES ARE CREATED DIRECTLY IN THE ISOLATED SCHEMA BY MIGRATION 0000.
-- THIS MIGRATION INTENTIONALLY REMAINS AS A NO-OP SO THE PUBLISHED MIGRATION
-- JOURNAL STAYS APPEND-ONLY WHILE NO UNRELATED PUBLIC TABLES ARE MOVED.
SELECT 1;
