ALTER TABLE "idoc"."seminar_registrations" ALTER COLUMN "profile_id" DROP NOT NULL;
ALTER TABLE "idoc"."seminar_registrations" ADD COLUMN "payment_method_canonical_id" varchar(40);
ALTER TABLE "idoc"."seminar_registrations" ADD COLUMN "guest_first_name" varchar(100);
ALTER TABLE "idoc"."seminar_registrations" ADD COLUMN "guest_last_name" varchar(100);
ALTER TABLE "idoc"."seminar_registrations" ADD COLUMN "guest_email" varchar(255);
ALTER TABLE "idoc"."seminar_registrations" ADD COLUMN "guest_phone" varchar(40);
ALTER TABLE "idoc"."seminar_registrations" ADD COLUMN "refunded_at" timestamp with time zone;
UPDATE "idoc"."seminar_registrations" r SET "payment_method_canonical_id" = s."payment_method_canonical_id" FROM "idoc"."seminars" s WHERE s.id = r.seminar_id;
ALTER TABLE "idoc"."seminar_registrations" ALTER COLUMN "payment_method_canonical_id" SET NOT NULL;
ALTER TABLE "idoc"."seminar_registrations" ADD CONSTRAINT "seminar_registrations_payment_method_canonical_id_seminar_payment_methods_canonical_id_fk" FOREIGN KEY ("payment_method_canonical_id") REFERENCES "idoc"."seminar_payment_methods"("canonical_id");
ALTER TABLE "idoc"."seminar_registrations" DROP CONSTRAINT "seminar_registrations_registration_status_check";
ALTER TABLE "idoc"."seminar_registrations" ADD CONSTRAINT "seminar_registrations_registration_status_check" CHECK ("registration_status" in ('registered','canceled','refunded'));
ALTER TABLE "idoc"."seminar_registrations" ADD CONSTRAINT "seminar_registrations_identity_check" CHECK (("profile_id" IS NOT NULL AND num_nonnulls("guest_first_name","guest_last_name","guest_email","guest_phone") = 0) OR ("profile_id" IS NULL AND num_nonnulls("guest_first_name","guest_last_name","guest_email","guest_phone") = 4));
CREATE UNIQUE INDEX "seminar_registrations_seminar_guest_email_unique" ON "idoc"."seminar_registrations" ("seminar_id", lower("guest_email")) WHERE "profile_id" IS NULL;
ALTER TABLE "idoc"."seminars" DROP CONSTRAINT "seminars_payment_method_canonical_id_seminar_payment_methods_canonical_id_fk";
ALTER TABLE "idoc"."seminars" DROP COLUMN "payment_method_canonical_id";
ALTER TABLE "idoc"."seminars" DROP COLUMN "timezone";
